import type {Metadata} from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ['100',"300","400","700","500","900"]
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} bg-background antialiased`}
      >
        <Banner />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
